"""Initial AI schema

Revision ID: baf7d117a48e
Revises: 
Create Date: 2026-08-15 21:41:00.930694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'baf7d117a48e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_eval_results_run_id'), 'eval_results', ['run_id'], unique=False, schema='ai')
    op.create_table('eval_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_table('job_results',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('command_id', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('job_id'),
    schema='ai'
    )
    op.create_table('llm_call_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('node', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_llm_call_logs_job_id'), 'llm_call_logs', ['job_id'], unique=False, schema='ai')
    op.create_index(op.f('ix_ai_llm_call_logs_trace_id'), 'llm_call_logs', ['trace_id'], unique=False, schema='ai')
    op.create_table('market_data_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=200), nullable=False),
    sa.Column('source_name', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_market_data_cache_cache_key'), 'market_data_cache', ['cache_key'], unique=True, schema='ai')
    op.create_table('prompt_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_prompt_versions_name'), 'prompt_versions', ['name'], unique=False, schema='ai')
    op.create_table('rag_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('category_code', sa.String(length=64), nullable=True),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(length=128), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('content_ko', sa.Text(), nullable=False),
    sa.Column('content_origin', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(1536), nullable=False),
    sa.Column('doc_hash', sa.String(length=80), nullable=True),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_rag_documents_country'), 'rag_documents', ['country'], unique=False, schema='ai')
    op.create_index('ix_rag_documents_embedding_hnsw', 'rag_documents', ['embedding'], unique=False, schema='ai', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_rag_documents_filter', 'rag_documents', ['country', 'document_type', 'effective_from'], unique=False, schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rag_documents_filter', table_name='rag_documents', schema='ai')
    op.drop_index('ix_rag_documents_embedding_hnsw', table_name='rag_documents', schema='ai', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_ai_rag_documents_country'), table_name='rag_documents', schema='ai')
    op.drop_table('rag_documents', schema='ai')
    op.drop_index(op.f('ix_ai_prompt_versions_name'), table_name='prompt_versions', schema='ai')
    op.drop_table('prompt_versions', schema='ai')
    op.drop_index(op.f('ix_ai_market_data_cache_cache_key'), table_name='market_data_cache', schema='ai')
    op.drop_table('market_data_cache', schema='ai')
    op.drop_index(op.f('ix_ai_llm_call_logs_trace_id'), table_name='llm_call_logs', schema='ai')
    op.drop_index(op.f('ix_ai_llm_call_logs_job_id'), table_name='llm_call_logs', schema='ai')
    op.drop_table('llm_call_logs', schema='ai')
    op.drop_table('job_results', schema='ai')
    op.drop_table('eval_runs', schema='ai')
    op.drop_index(op.f('ix_ai_eval_results_run_id'), table_name='eval_results', schema='ai')
    op.drop_table('eval_results', schema='ai')
    # ### end Alembic commands ###
